version: "3.8"

services:

  iam_service:
    build:
      context: ./IAM
      dockerfile: Dockerfile
    container_name: iam_service
    restart: always
    env_file:
      - ./IAM/.env
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

  profile_service:
    build:
      context: ./UserProfile
      dockerfile: Dockerfile
    container_name: profile_service
    restart: always
    env_file:
      - ./UserProfile/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./IAM/DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_server
    restart: unless-stopped
    ports:
      - "6379:6379"

  gateway:
    image: nginx:latest
    container_name: api_gateway
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy_common.conf:/etc/nginx/conf.d/proxy_common.conf:ro
    depends_on:
      - iam_service
      - profile_service

volumes:
  pgdata:
