version: "3.8"

services:

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"

  iam_service:
    build:
      context: ./IAM
      dockerfile: Dockerfile
    container_name: iam_service
    restart: always
    env_file:
      - ./IAM/.env
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "3000:3000"

  profile_service:
    build:
      context: .
      dockerfile: UserProfile/Dockerfile
    container_name: profile_service
    restart: always
    env_file:
      - ./UserProfile/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"

  group_service:
    build:
      context: .
      dockerfile: Group/Dockerfile
    container_name: group_service
    restart: always
    env_file:
      - ./Group/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "3002:3002"

  study_service:
    build:
      context: .
      dockerfile: Study/Dockerfile
    container_name: study_service
    restart: always
    env_file:
      - ./Study/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "3003:3003"

  media_service:
    build:
      context: .
      dockerfile: Media/Dockerfile
    container_name: media_service
    restart: always
    env_file:
      - ./Media/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3004:3004"

  chat_service:
    build:
      context: .
      dockerfile: Chat/Dockerfile
    container_name: chat_service
    restart: always
    env_file:
      - ./Chat/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      group_service:
        condition: service_started
    ports:
      - "3006:3006"

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_server
    restart: unless-stopped
    ports:
      - "6379:6379"

  gateway:
    image: nginx:latest
    container_name: api_gateway
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy_common.conf:/etc/nginx/conf.d/proxy_common.conf:ro
    depends_on:
      - iam_service
      - profile_service
      - group_service
      - study_service
      - media_service
      - chat_service

volumes:
  pgdata:
