app = "mahta-rabbitmq-2026"
primary_region = "fra"

[build]
  dockerfile = "/Dockerfile"

[[mounts]]
  source = "rabbitmq_data"
  destination = "/var/lib/rabbitmq"

[[services]]
  internal_port = 5672
  protocol = "tcp"

  [[services.ports]]
    port = 5672

[[services]]
  internal_port = 15672
  protocol = "tcp"

  [[services.ports]]
    port = 15672
